# Generated by Django 3.0.2 on 2020-01-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swjoke', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SithPlanets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planet_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='recruit',
            name='recruit_planet',
            field=models.CharField(choices=[('Ashas Ree', 'Ashas Ree'), ('Athiss', 'Athiss'), ('Begeren', 'Begeren'), ('Bosthirda', 'Bosthirda'), ("Ch'hodos", "Ch'hodos"), ('Dromund Fels', 'Dromund Fels'), ('Dromund Ixin', 'Dromund Ixin'), ('Dromund Kaas', 'Dromund Kaas'), ('Dromund Kalakar', 'Dromund Kalakar'), ('Kalakar Six', 'Kalakar Six'), ('Dromund Tyne', 'Dromund Tyne'), ('Jaguada', 'Jaguada'), ("Jaguada's moon", "Jaguada's moon"), ('Kalsunor', 'Kalsunor'), ('Khar Delba', 'Khar Delba'), ('Khar Shian', 'Khar Shian'), ('Korriban', 'Korriban'), ('Korriz', 'Korriz'), ('Krayiss Two', 'Krayiss Two'), ('Nfolgai', 'Nfolgai'), ('Rhelg', 'Rhelg'), ('Ziost', 'Ziost')], default='Ashas Ree', max_length=20),
        ),
        migrations.AlterField(
            model_name='sith',
            name='sith_planet',
            field=models.CharField(choices=[('Ashas Ree', 'Ashas Ree'), ('Athiss', 'Athiss'), ('Begeren', 'Begeren'), ('Bosthirda', 'Bosthirda'), ("Ch'hodos", "Ch'hodos"), ('Dromund Fels', 'Dromund Fels'), ('Dromund Ixin', 'Dromund Ixin'), ('Dromund Kaas', 'Dromund Kaas'), ('Dromund Kalakar', 'Dromund Kalakar'), ('Kalakar Six', 'Kalakar Six'), ('Dromund Tyne', 'Dromund Tyne'), ('Jaguada', 'Jaguada'), ("Jaguada's moon", "Jaguada's moon"), ('Kalsunor', 'Kalsunor'), ('Khar Delba', 'Khar Delba'), ('Khar Shian', 'Khar Shian'), ('Korriban', 'Korriban'), ('Korriz', 'Korriz'), ('Krayiss Two', 'Krayiss Two'), ('Nfolgai', 'Nfolgai'), ('Rhelg', 'Rhelg'), ('Ziost', 'Ziost')], default='Ashas Ree', max_length=20),
        ),
    ]
