# Generated by Django 3.0.2 on 2020-02-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swjoke', '0002_auto_20200205_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('answer', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='recruit_questions',
        ),
        migrations.RemoveField(
            model_name='test',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='question_text',
        ),
        migrations.AddField(
            model_name='recruit',
            name='recruit_test',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='swjoke.Test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(blank=True, to='swjoke.Question'),
        ),
    ]
