# Generated by Django 3.0.2 on 2020-02-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swjoke', '0003_auto_20200206_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='recruit_planet',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='recruit_test',
        ),
        migrations.RemoveField(
            model_name='sith',
            name='sith_planet',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='Recruit',
        ),
        migrations.DeleteModel(
            name='Sith',
        ),
        migrations.DeleteModel(
            name='SithPlanets',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
