# Generated by Django 3.0.2 on 2020-02-06 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swjoke', '0005_question_recruit_sith_sithplanets_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AlterField(
            model_name='recruit',
            name='recruit_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='swjoke.Test'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swjoke.Question')),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swjoke.Recruit')),
            ],
        ),
    ]
